name: KuerbissKraft
version: 0.1.0
description: Game management plugin
main: main.Loader

commands:
  kurbiss:
    description: varo options
  kürbiss:
    description: varo options
  kuerbiss:
    description: varo options
  kurbis:
    description: varo options
  kürbis:
    description: varo options
  kuerbis:
    description: varo options
